GET localhost:8080/auth/login
Content-Type: application/json

{
  "email": "admin@mail.ru",
  "password": "pwd"
}


###

GET localhost:8080/auth/login
Content-Type: application/json

{
  "email": "testuser3@mail.ru",
  "password": "P@ssw0rd"
}