POST localhost:8080/auth/reg/1
Content-Type: application/json

{
"name": "testuser2",
"password": "userpassw",
"email": "testuser2@mail.ru"
}

###

POST localhost:8080/auth/reg/1
Content-Type: application/json

{
  "name": "testuser3",
  "password": "password",
  "email": "testuser2@mail.ru"
}