### админ создает пользователя

POST localhost:8080/persons/add
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJFbWFpbCI6ImFkbWluQG1haWwucnUiLCJSb2xlIjoiYWRtaW4iLCJOYW1lIjoiQWRtaW4ifQ.uVY6lFP4hNVxncSDhsJZdbHyLxhhg2RQDh6HtT3va4s
Content-Type: application/json

{
  "name": "test-user",
  "password": "P@ssw0rd",
  "email": "test-user@mail.ru"
}

