### Админ добавляет книгу (дубль)

POST localhost:8080/books/add
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJFbWFpbCI6ImFkbWluQG1haWwucnUiLCJSb2xlIjoiYWRtaW4iLCJOYW1lIjoiQWRtaW4iLCJpZCI6MX0.REK6plXcU7764jUqAB2-vA1QdV4-5kNq8-tEKGyyKRQ
Content-Type: application/json

{
  "name": "Хорошая книга 4",
  "author": "Я и он",
  "yearOfProduction": 2021,
  "annotation": "читать по любому"
}


###  Админ добавляет книгу
POST localhost:8080/books/add
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJFbWFpbCI6ImFkbWluQG1haWwucnUiLCJSb2xlIjoiYWRtaW4iLCJOYW1lIjoiQWRtaW4iLCJpZCI6MX0.REK6plXcU7764jUqAB2-vA1QdV4-5kNq8-tEKGyyKRQ
Content-Type: application/json

{
  "name": "Новый ребенок к пятнице. Воспитание без криков и наказаний за 5 дней",
  "author": "Леман Кевин",
  "yearOfProduction": 2021,
  "annotation": "Лучшие методики по воспитанию - в одной книге!"
}